<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_admin4</name>
   <tag></tag>
   <elementGuidId>63bd69f9-2be1-450d-88cd-6857150bf07b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mr-2.d-none.d-lg-inline.text-gray-600.small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='userDropdown']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dc0310f8-6156-4f4a-b5ca-6c01a4ad50fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 d-none d-lg-inline text-gray-600 small</value>
      <webElementGuid>4db9eb46-1238-488f-9498-0b3781f39b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>admin4</value>
      <webElementGuid>c2d525a6-abf1-4212-963a-84689a322192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDropdown&quot;)/span[@class=&quot;mr-2 d-none d-lg-inline text-gray-600 small&quot;]</value>
      <webElementGuid>f17ba606-ce11-474f-bed5-67c227ed13cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userDropdown']/span</value>
      <webElementGuid>3041faf8-989a-4a5a-bee5-dc157a81d568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pengeluaran'])[1]/following::span[1]</value>
      <webElementGuid>abc331b8-3e70-4d5c-95d4-432dce1af00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catat Pengeluaran'])[1]/following::span[1]</value>
      <webElementGuid>a8f31b54-2654-483f-97b3-892248ed2faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='admin4']/parent::*</value>
      <webElementGuid>ddb8658d-8ae4-4e63-9d6b-dbe1100c965b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a/span</value>
      <webElementGuid>81bf7236-73df-4712-88e3-f982bedb6203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'admin4' or . = 'admin4')]</value>
      <webElementGuid>821d7522-73a2-45f3-94cb-adf504bfe2a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
