<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_100</name>
   <tag></tag>
   <elementGuidId>8a2b39d7-9a97-426f-b7ba-c8a8aae4c7f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(25) > td:nth-of-type(3)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='tes tambah'])[1]/following::td[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e0494e35-b2a4-42c0-a598-7e06dace9cc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e18f2260-b3ce-4994-b0ee-e1785602ba1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/center[1]/table[@class=&quot;mt-4&quot;]/tbody[1]/tr[25]/td[3]</value>
      <webElementGuid>0f109bb1-fd96-4841-9b02-a0ae1e0cb728</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='tes tambah'])[1]/following::td[1]</value>
      <webElementGuid>cdf0ca2e-7a28-4204-b92f-d8852db638a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farid'])[1]/following::td[9]</value>
      <webElementGuid>a309abe6-df94-4b94-8ff5-e660dfc778fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td[3]</value>
      <webElementGuid>e22f6c9a-c5d5-45e3-bdb8-0587c548dce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '100' or . = '100')]</value>
      <webElementGuid>a3ecc6e8-4ca3-4768-94ac-ec0acd99b70f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
