<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_addmin</name>
   <tag></tag>
   <elementGuidId>57127d6e-8e3d-44e4-b6dc-8680b96581f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mr-2.d-none.d-lg-inline.text-gray-600.small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='userDropdown']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f905d1a1-9f80-4aa8-9934-ee5b1cc6bce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 d-none d-lg-inline text-gray-600 small</value>
      <webElementGuid>527e0e43-2436-4f7e-bb0d-e42540d9bb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>addmin</value>
      <webElementGuid>481c019f-9a6a-4963-975f-43ff72c30ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDropdown&quot;)/span[@class=&quot;mr-2 d-none d-lg-inline text-gray-600 small&quot;]</value>
      <webElementGuid>a0d1c7ec-a047-4b2f-8392-20e6d89e2b9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userDropdown']/span</value>
      <webElementGuid>113956b3-88ca-4850-8543-db397e0f7fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pengeluaran'])[1]/following::span[1]</value>
      <webElementGuid>c3aba601-6c49-4028-ad61-4825831708a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catat Pengeluaran'])[1]/following::span[1]</value>
      <webElementGuid>952b5c94-c6a1-41ce-8119-1c0bda9051b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='addmin']/parent::*</value>
      <webElementGuid>50f822e4-cdf4-4f92-8b18-67c9be843d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a/span</value>
      <webElementGuid>5a5fce2f-68b1-413f-8035-6914301b55c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'addmin' or . = 'addmin')]</value>
      <webElementGuid>86eaafdf-6c71-4e22-969b-36b3ba9e5702</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
