<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_admin4_img-profile rounded-circle</name>
   <tag></tag>
   <elementGuidId>75f6bf3f-c387-4c09-8365-916994c3e8ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.img-profile.rounded-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='userDropdown']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5d983b59-9c00-4840-a94d-14b73741f82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-profile rounded-circle</value>
      <webElementGuid>88d8bcf6-82eb-4628-8208-4ed898ca3086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>img/Place Image.jpg</value>
      <webElementGuid>fd7d2463-163d-4752-b5ae-0a4d9c67be06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>profile</value>
      <webElementGuid>e602ee6d-0b27-4a1d-ba72-1cd7cc17c838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDropdown&quot;)/img[@class=&quot;img-profile rounded-circle&quot;]</value>
      <webElementGuid>4b1adc15-d7bc-4854-b6d4-386baf34b70c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userDropdown']/img</value>
      <webElementGuid>86ed2a28-2a7e-45f7-a084-fbf6c30f89a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='profile']</value>
      <webElementGuid>97090043-e1a9-4245-b39c-d38e7b032e2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>f9dde34a-d820-4920-8d53-5e44e0eb2cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'img/Place Image.jpg' and @alt = 'profile']</value>
      <webElementGuid>2b53c7e9-df3a-482b-a306-c9b2f24d9738</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
