<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_adminaaa</name>
   <tag></tag>
   <elementGuidId>32248244-3656-453b-bed3-ac0ebf2c18b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.mr-2.d-none.d-lg-inline.text-gray-600.small</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='userDropdown']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1d6d7d1e-45d9-4e34-83ab-7e01e4336e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 d-none d-lg-inline text-gray-600 small</value>
      <webElementGuid>ae35f76f-dbf8-454d-b235-b9287273692d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>adminaaa</value>
      <webElementGuid>cac860d5-c0a1-43ab-a57e-38b017ccdfc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;userDropdown&quot;)/span[@class=&quot;mr-2 d-none d-lg-inline text-gray-600 small&quot;]</value>
      <webElementGuid>596ea9c8-5fe0-453f-bc88-fc72ce782053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='userDropdown']/span</value>
      <webElementGuid>eee33e66-41db-4903-8ffa-902bede927a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Pengeluaran'])[1]/following::span[1]</value>
      <webElementGuid>2ab55047-138e-4b97-a132-bc90a4a1850b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Catat Pengeluaran'])[1]/following::span[1]</value>
      <webElementGuid>79634333-e9e3-49d9-a019-3ad48968d488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='adminaaa']/parent::*</value>
      <webElementGuid>128f01a5-08f2-48dd-a3d5-6bd60ad87105</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/ul/li/a/span</value>
      <webElementGuid>d00aa82e-91b6-4e79-80c0-ffe4ed2b222e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'adminaaa' or . = 'adminaaa')]</value>
      <webElementGuid>0638d30e-b043-4986-9ef3-125985e8efb5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
